### ISSUE TITLE
Ref's to Schemas which 404

### ISSUE THREAD

**Issue by ghost** [thill-odi/conformance-profiles#2]
core/Event.json $ref's to things like https://www.openactive.io/core/concept.schema.json which 404

Is this intentional?

Can they ref to working links?

**Comment by ghost** [comment]
Are all the ref's meant to be to the JSON Schema files in this repository, or should some be to files outside this repository?

**Comment by thill-odi** [comment]
Sorry, should have been clear about this - the references are purely ids and do not resolve. The repo (and indeed each individual directory) is meant to be self-contained.

**Comment by ghost** [comment]
Ok, thanks
