### ISSUE TITLE
socialrx/Activity.json

### ISSUE THREAD

**Issue by ghost** [thill-odi/conformance-profiles#4]
This requires a Type "Concept" - several of the types I found in socialrx ho

**Comment by thill-odi** [comment]
That's in fact correct - `activity`, `level`, and `accessibilitySupport` are all `skos:Concepts`; in some cases, however, the set of attributes considered to be `required` differs, hence the need for separate schemas.

The way the files were split out, however, did not make this very clear. I've added a distinct file for `Level`, which hopefully makes the pattern a little more obvious.

See https://github.com/openactive/conformance-profiles/commit/e08c59e3990344287b635610e69e26617a050ebc
